# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "ed1dbbde346ce4a411907e6a4e456390"
name = "facebook_catelog"
handle = "facebook-catelog"
application_url = "http://127.0.0.1:9237"
embedded = true

[build]
automatically_update_urls_on_dev = true
include_config_on_deploy = true

[webhooks]
api_version = "2026-04"

[access_scopes]
scopes = "read_products"
optional_scopes = [ ]
use_legacy_install_flow = false

[auth]
redirect_urls = [ ]
